name: Node.js Package

trigger:
  branches:
    include:
      - main

jobs:
  build:
    runs-on: Windows
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - run: npm install 
      - run: npm test
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
