name: Node.js Package

trigger:
  branches:
    include:
      - main

jobs:
  build:
    runs-on: Windows
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - name: Install dependencies
        run: npm install 
      - name: Install Playwright
        run: npm install playwright
      - name: Run tests
        run: npm test
      - name: Publish package
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}

